name: make-lint
on: [push]
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - run: make lint

      - run: |
          pip install poetry
          make install
      - name: Run linter and pytest
        run: |
          make check
