name: make-lint

on:
  - push
  - pull_request
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pip install poetry
          make install
      - name: Run linter and pytest
        run: |
          make check
